### ISSUE TITLE
Issues while attacking forts

### ISSUE THREAD

**Issue by Soyuz247** [PiratesAhoy/new-horizons#180] opened 2023-12-02 17:11 UTC
Only front cannons work in capturing forts, broadsides does nothing.

Unless there are ships nearby, a heavy spike lag could be experienced when near forts. 

Unless there are ships nearby, attacking the fort doesn't work

There is a crash right after the capturing fort for myself dialog

**Comment by tommy61157** [comment] 2023-12-03 02:21
Duplicate of #83

**Comment by tommy61157** [comment] 2023-12-03 15:45
I'm going to close this as this is a duplicate issue and Hammie already has this marked for completion for the beta

**Closed by tommy61157** 2023-12-03 15:45 UTC
